name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          make deps

      - name: Read version from .version
        id: version
        run: |
          VERSION=$(cat .version | tr -d '\n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build binaries for AMD64 and ARM64 with version
        run: |
          make build-linux

      - name: Verify config/config.json exists
        run: |
          if [ ! -f config/config.json ]; then
            echo "Error: config/config.json not found"
            exit 1
          fi

      - name: Set up Multipass
        run: |
          # Install snapd and Multipass with retries
          sudo apt-get update
          sudo apt-get install -y snapd openssh-client
          for i in {1..3}; do
            sudo snap install multipass --classic --channel 1.14/stable && break
            echo "Multipass install failed, retrying ($i/3)..."
            sleep 10
          done || (echo "Failed to install Multipass after 3 attempts" && exit 1)

          # Ensure Multipass daemon is running and accessible
          sudo systemctl enable snapd.socket --now
          sudo systemctl start snap.multipass.multipassd.service || true  # Start if not running
          sleep 5  # Give daemon tim
